explorer/urls.py
from django.urls import path, re_path

from explorer.views import (
    CreateQueryView, DeleteQueryView, DownloadFromSqlView, DownloadQueryView, EmailCsvQueryView, ListQueryLogView,
    ListQueryView, PlayQueryView, QueryView, SchemaView, StreamQueryView, format_sql,
)


urlpatterns = [
    path(
        '<int:query_id>/', QueryView.as_view(), name='query_detail'
    ),
    path(
        '<int:query_id>/download', DownloadQueryView.as_view(),
        name='download_query'
    ),
    path(
        '<int:query_id>/stream', StreamQueryView.as_view(),
        name='stream_query'
    ),
    path('download', DownloadFromSqlView.as_view(), name='download_sql'),
    path(
        '<int:query_id>/email_csv', EmailCsvQueryView.as_view(),
        name='email_csv_query'
    ),
    path(
        '<int:pk>/delete', DeleteQueryView.as_view(), name='query_delete'
    ),
    path('new/', CreateQueryView.as_view(), name='query_create'),
    path('play/', PlayQueryView.as_view(), name='explorer_playground'),
    re_path(
        r'schema/(?P<connection>.+)$', SchemaView.as_view(),
        name='explorer_schema'
    ),
    path('logs/', ListQueryLogView.as_view(), name='explorer_logs'),
    path('format/', format_sql, name='format_sql'),
    path('', ListQueryView.as_view(), name='explorer_index'),
]

explorer/models.py
import logging
from time import time

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import DatabaseError, models, transaction
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from explorer import app_settings
from explorer.utils import (
    extract_params, get_params_for_url, get_s3_bucket, get_valid_connection, passes_blacklist, s3_url,
    shared_dict_update, swap_params,
)


MSG_FAILED_BLACKLIST = "Query failed the SQL blacklist: %s"

logger = logging.getLogger(__name__)


class Query(models.Model):
    title = models.CharField(max_length=255)
    sql = models.TextField(blank=False, null=False)
    description = models.TextField(blank=True)
    created_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    last_run_date = models.DateTimeField(auto_now=True)
    snapshot = models.BooleanField(
        default=False,
        help_text=_("Include in snapshot task (if enabled)")
    )
    connection = models.CharField(
        blank=True,
        max_length=128,
        default='',
        help_text=_(
            "Name of DB connection (as specified in settings) to use for "
            "this query."
            "Will use EXPLORER_DEFAULT_CONNECTION if left blank"
        )
    )

    def __init__(self, *args, **kwargs):
        self.params = kwargs.get('params')
        kwargs.pop('params', None)
        super().__init__(*args, **kwargs)

    class Meta:
        ordering = ['title']
        verbose_name = _('Query')
        verbose_name_plural = _('Queries')

    def __str__(self):
        return str(self.title)

    def get_run_count(self):
        return self.querylog_set.count()

    def avg_duration(self):
        return self.querylog_set.aggregate(
            models.Avg('duration')
        )['duration__avg']

    def passes_blacklist(self):
        return passes_blacklist(self.final_sql())

    def final_sql(self):
        return swap_params(self.sql, self.available_params())

    def execute_query_only(self):
        # check blacklist every time sql is run to catch parameterized SQL
        passes_blacklist_flag, failing_words = self.passes_blacklist()

        error = MSG_FAILED_BLACKLIST % ', '.join(
            failing_words) if not passes_blacklist_flag else None

        if error:
            raise ValidationError(
                error,
                code="InvalidSql"
            )

        return QueryResult(
            self.final_sql(), get_valid_connection(self.connection)
        )

    def execute_with_logging(self, executing_user):
        ql = self.log(executing_user)
        ret = self.execute()
        ql.duration = ret.duration
        ql.save()
        return ret, ql

    def execute(self):
        ret = self.execute_query_only()
        ret.process()
        return ret

    def available_params(self):
        """
        Merge parameter values into a dictionary of available parameters

        :return: A merged dictionary of parameter names and values.
                 Values of non-existent parameters are removed.
        :rtype: dict
        """
        p = extract_params(self.sql)
        if self.params:
            shared_dict_update(p, self.params)
        return p

    def get_absolute_url(self):
        return reverse("query_detail", kwargs={'query_id': self.id})

    @property
    def params_for_url(self):
        return get_params_for_url(self)

    def log(self, user=None):
        if user:
            if user.is_anonymous:
                user = None
        ql = QueryLog(
            sql=self.final_sql(),
            query_id=self.id,
            run_by_user=user,
            connection=self.connection
        )
        ql.save()
        return ql

    @property
    def shared(self):
        return self.id in set(
            sum(app_settings.EXPLORER_GET_USER_QUERY_VIEWS().values(), [])
        )

    @property
    def snapshots(self):
        if app_settings.ENABLE_TASKS:
            b = get_s3_bucket()
            objects = b.objects.filter(Prefix=f'query-{self.id}/snap-')
            objects_s = sorted(objects, key=lambda k: k.last_modified)
            return [
                SnapShot(
                    s3_url(b, o.key),
                    o.last_modified
                ) for o in objects_s
            ]


class SnapShot:

    def __init__(self, url, last_modified):
        self.url = url
        self.last_modified = last_modified


class QueryLog(models.Model):
    sql = models.TextField(blank=True)
    query = models.ForeignKey(
        Query,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    run_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    run_at = models.DateTimeField(auto_now_add=True)
    duration = models.FloatField(blank=True, null=True)  # milliseconds
    connection = models.CharField(blank=True, max_length=128, default='')

    @property
    def is_playground(self):
        return self.query_id is None

    class Meta:
        ordering = ['-run_at']


class QueryResult:

    def __init__(self, sql, connection):

        self.sql = sql
        self.connection = connection

        cursor, duration = self.execute_query()

        self._description = cursor.description or []
        self._data = [list(r) for r in cursor.fetchall()]
        self.duration = duration

        cursor.close()

        self._headers = self._get_headers()
        self._summary = {}

    @property
    def data(self):
        return self._data or []

    @property
    def headers(self):
        return self._headers or []

    @property
    def header_strings(self):
        return [str(h) for h in self.headers]

    def _get_headers(self):
        return [
            ColumnHeader(d[0]) for d in self._description
        ] if self._description else [ColumnHeader('--')]

    def _get_numerics(self):
        if hasattr(self.connection.Database, "NUMBER"):
            return [
                ix for ix, c in enumerate(self._description)
                if hasattr(c, 'type_code') and c.type_code in self.connection.Database.NUMBER.values
            ]
        elif self.data:
            d = self.data[0]
            return [
                ix for ix, _ in enumerate(self._description)
                if not isinstance(d[ix], str) and str(d[ix]).isnumeric()
            ]
        return []

    def _get_transforms(self):
        transforms = dict(app_settings.EXPLORER_TRANSFORMS)
        return [
            (ix, transforms[str(h)])
            for ix, h in enumerate(self.headers) if str(h) in transforms.keys()
        ]

    def column(self, ix):
        return [r[ix] for r in self.data]

    def process(self):
        start_time = time()

        self.process_columns()
        self.process_rows()

        logger.info("Explorer Query Processing took %sms." % ((time() - start_time) * 1000))

    def process_columns(self):
        for ix in self._get_numerics():
            self.headers[ix].add_summary(self.column(ix))

    def process_rows(self):
        transforms = self._get_transforms()
        if transforms:
            for r in self.data:
                for ix, t in transforms:
                    r[ix] = t.format(str(r[ix]))

    def execute_query(self):
        cursor = self.connection.cursor()
        start_time = time()

        try:
            with transaction.atomic(self.connection.alias):
                cursor.execute(self.sql)
        except DatabaseError as e:
            cursor.close()
            raise e

        return cursor, ((time() - start_time) * 1000)


class ColumnHeader:

    def __init__(self, title):
        self.title = title.strip()
        self.summary = None

    def add_summary(self, column):
        self.summary = ColumnSummary(self, column)

    def __str__(self):
        return self.title


class ColumnStat:

    def __init__(self, label, statfn, precision=2, handles_null=False):
        self.label = label
        self.statfn = statfn
        self.precision = precision
        self.handles_null = handles_null

    def __call__(self, coldata):
        self.value = round(
            float(self.statfn(coldata)), self.precision
        ) if coldata else 0

    def __str__(self):
        return self.label


class ColumnSummary:

    def __init__(self, header, col):
        self._header = header
        self._stats = [
            ColumnStat("Sum", sum),
            ColumnStat("Avg", lambda x: float(sum(x)) / float(len(x))),
            ColumnStat("Min", min),
            ColumnStat("Max", max),
            ColumnStat("NUL", lambda x: int(sum(map(lambda y: 1 if y is None else 0, x))), 0, True)
        ]
        without_nulls = list(map(lambda x: 0 if x is None else x, col))

        for stat in self._stats:
            stat(col) if stat.handles_null else stat(without_nulls)

    @property
    def stats(self):
        return {c.label: c.value for c in self._stats}

    def __str__(self):
        return str(self._header)

explorer/views/create.py
from django.views.generic import CreateView

from explorer.forms import QueryForm
from explorer.views.auth import PermissionRequiredMixin
from explorer.views.mixins import ExplorerContextMixin


class CreateQueryView(PermissionRequiredMixin, ExplorerContextMixin,
                      CreateView):

    permission_required = 'change_permission'
    form_class = QueryForm
    template_name = 'explorer/query.html'

    def form_valid(self, form):
        form.instance.created_by_user = self.request.user
        return super().form_valid(form)

explorer/views/delete.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from explorer.models import Query
from explorer.views.auth import PermissionRequiredMixin
from explorer.views.mixins import ExplorerContextMixin


class DeleteQueryView(PermissionRequiredMixin, ExplorerContextMixin,
                      DeleteView):

    permission_required = 'change_permission'
    model = Query
    success_url = reverse_lazy("explorer_index")

explorer/views/download.py
from django.shortcuts import get_object_or_404
from django.views.generic.base import View

from explorer.models import Query
from explorer.views.auth import PermissionRequiredMixin
from explorer.views.export import _export


class DownloadQueryView(PermissionRequiredMixin, View):

    permission_required = 'view_permission'

    def get(self, request, query_id, *args, **kwargs):
        query = get_object_or_404(Query, pk=query_id)
        return _export(request, query)


class DownloadFromSqlView(PermissionRequiredMixin, View):

    permission_required = 'view_permission'

    def post(self, request, *args, **kwargs):
        sql = request.POST.get('sql', '')
        connection = request.POST.get('connection', '')
        query = Query(sql=sql, connection=connection, title='')
        ql = query.log(request.user)
        query.title = f'Playground-{ql.id}'
        return _export(request, query)

explorer/views/email.py
from django.http import JsonResponse
from django.views import View

from explorer.tasks import execute_query
from explorer.views.auth import PermissionRequiredMixin


class EmailCsvQueryView(PermissionRequiredMixin, View):

    permission_required = 'view_permission'

    def post(self, request, query_id, *args, **kwargs):
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            email = request.POST.get('email', None)
            if email:
                execute_query.delay(query_id, email)
                return JsonResponse(
                    {'message': 'message was sent successfully'}
                )
        return JsonResponse({}, status=403)

explorer/views/export.py
from django.db import DatabaseError
from django.http import HttpResponse

from explorer.exporters import get_exporter_class
from explorer.utils import url_get_params


def _export(request, query, download=True):
    _fmt = request.GET.get('format', 'csv')
    exporter_class = get_exporter_class(_fmt)
    query.params = url_get_params(request)
    delim = request.GET.get('delim')
    exporter = exporter_class(query)
    try:
        output = exporter.get_output(delim=delim)
    except DatabaseError as e:
        msg = f"Error executing query {query.title}: {e}"
        return HttpResponse(
            msg, status=500
        )

    response = HttpResponse(
        output,
        content_type=exporter.content_type
    )
    if download:
        response['Content-Disposition'] = \
            f'attachment; filename="{exporter.get_filename()}"'
    return response

explorer/views/format_sql.py
from django.http import JsonResponse
from django.views.decorators.http import require_POST

from explorer.utils import fmt_sql


@require_POST
def format_sql(request):
    sql = request.POST.get('sql', '')
    formatted = fmt_sql(sql)
    return JsonResponse({"formatted": formatted})

explorer/views/mixins.py
from django.conf import settings
from django.shortcuts import render

from explorer import app_settings


class ExplorerContextMixin:

    def gen_ctx(self):
        return {
            'can_view': app_settings.EXPLORER_PERMISSION_VIEW(
                self.request
            ),
            'can_change': app_settings.EXPLORER_PERMISSION_CHANGE(
                self.request
            ),
            'csrf_cookie_name': settings.CSRF_COOKIE_NAME,
            'view_name': self.request.resolver_match.view_name,
        }

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update(self.gen_ctx())
        return ctx

    def render_template(self, template, ctx):
        ctx.update(self.gen_ctx())
        return render(self.request, template, ctx)

explorer/views/schema.py
from django.http import Http404
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.clickjacking import xframe_options_sameorigin

from explorer.connections import connections
from explorer.schema import schema_info
from explorer.views.auth import PermissionRequiredMixin


class SchemaView(PermissionRequiredMixin, View):

    permission_required = 'change_permission'

    @method_decorator(xframe_options_sameorigin)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        connection = kwargs.get('connection', '')
        if connection not in connections:
            raise Http404
        schema = schema_info(connection)
        if schema:
            return render(
                request,
                'explorer/schema.html',
                {'schema': schema_info(connection)}
            )
        else:
            return render(request, 'explorer/schema_building.html')

explorer/views/stream.py
from django.shortcuts import get_object_or_404
from django.views import View

from explorer.models import Query
from explorer.views.auth import PermissionRequiredMixin
from explorer.views.export import _export


class StreamQueryView(PermissionRequiredMixin, View):

    permission_required = 'view_permission'

    def get(self, request, query_id, *args, **kwargs):
        query = get_object_or_404(Query, pk=query_id)
        return _export(request, query, download=False)

explorer/templates/explorer/play.html
{% extends "explorer/base.html" %}
{% load explorer_tags i18n %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="col-md-12">
        <h2>{% trans "Playground" %}</h2>
        <p>
            {% blocktrans trimmed %}
                The playground is for experimenting and writing ad-hoc queries. By default, nothing you do here will be saved.
            {% endblocktrans %}
        </p>
        <form role="form" action="{% url 'explorer_playground' %}" method="post" id="editor" class="playground-form form-horizontal">{% csrf_token %}
            {% if error %}
                <div class="alert alert-danger">{{ error|escape }}</div>
            {% endif %}
            {% if form.connections|length > 1 %}
                <div class="form-group">
                    <label for="id_connection" class="col-sm-2 control-label">{% trans "Connection" %}</label>
                    <div class="col-sm-10">
                        {{ form.connection }}
                    </div>
                </div>
            {% else %}
                {# still need to submit the connection, just hide the UI element #}
                <div class="hidden">
                    {{ form.connection }}
                </div>
            {% endif %}
            <div class="panel panel-default sql-panel">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-6">
                            <span class="panel-title">{% trans "Playground SQL" %}</span>
                        </div>
                        {% if ql_id %}
                            <div class="col-md-6 text-right">
                                <small>
                                    <a href="{% url 'explorer_playground' %}?querylog_id={{ ql_id }}">
                                        <i class="glyphicon glyphicon-link"></i>
                                    </a>
                                </small>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="panel-content">
                    <textarea class="form-control" cols="40" id="id_sql" name="sql" rows="20">{{ query.sql }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="text-center">
                    <div class="btn-group">
                        <input type="submit" value="{% trans 'Run' %}" id="refresh_play_button" class="btn btn-default"/>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><input type="submit" value="{% trans 'Save As New Query' %}" id="create_button" class="btn btn-link"/></li>
                        </ul>
                    </div>
                    <div class="btn-group">
                        <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% trans "Download" %}
                        </label>
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                        </button>
                        <ul class="dropdown-menu">
                            {% export_buttons query %}
                        </ul>
                    </div>

                    <button type="button" class="btn btn-default" id="show_schema_button">
                        {% trans "Show Schema" %}
                    </button>
                    <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">
                        {% trans "Hide Schema" %}
                    </button>
                    <button type="button" class="btn btn-default" id="format_button">
                        {% trans "Format" %}
                    </button>
                    <button type="button" class="btn btn-default" id="format_button">
                        {% trans "Open IDE" %}
                    </button>
                </div>
            </div>
            <input type="hidden" value="{% trans 'Playground Query' %}" name="title" />
        </form>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="about:blank" height="828px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>
{% include 'explorer/preview_pane.html' %}

{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId);
        });
    </script>
{% endblock %}

explorer/templates/explorer/query.html
{% extends "explorer/base.html" %}
{% load explorer_tags i18n %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="query-area col-md-12">
        {% spaceless %}
            <h2>
                {% if query %}
                    {{ query.title }}
                    {% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}
                {% else %}
                    {% trans "New Query" %}
                {% endif %}
            </h2>
        {% endspaceless %}
        {% if query %}
            <div class="text-right">
                <a href="{% url 'explorer_logs' %}?query_id={{ query.id }}">
                    <h2 class="small">{% trans "History" %}</h2>
                </a>
            </div>
        {% endif %}
        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
        <div>
            {% if query %}
                <form role="form" class="form-horizontal" action="{% url 'query_detail' query.id %}" method="post" id="editor">{% csrf_token %}
            {% else %}
                <form role="form" class="form-horizontal" action="{% url 'query_create' %}" method="post" id="editor">{% csrf_token %}
            {% endif %}
                {% if error %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endif %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {% if form.title.errors %}{% for error in form.title.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}{% endif %}
                    <label for="id_title" class="col-sm-2 control-label">{% trans "Title" %}</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="id_title" maxlength="255" name="title" type="text" {% if not can_change %}disabled{% endif %} value="{{ form.title.value|default_if_none:"" }}" />
                    </div>
                {% if form.connections|length > 1 and can_change %}
                </div>
                <div class="form-group">
                    <label for="id_connection" class="col-sm-2 control-label">{% trans "Connection" %}</label>
                    <div class="col-sm-10">
                        {{ form.connection }}
                    </div>
                {% else %}
                    {# still need to submit the connection, just hide the UI element #}
                    <div class="hidden">
                      {{ form.connection }}
                    </div>
                {% endif %}
                </div>
                <div class="form-group">
                    {% if form.description.errors %}
                        <div class="alert alert-danger">{{ form.description.errors }}</div>
                    {% endif %}
                    <label for="id_description" class="col-sm-2 control-label">
                        {% trans "Description"%}
                    </label>
                    <div class="col-sm-10">
                        <textarea
                            id="id_description" class="form-control" cols="40" name="description"
                            {% if not can_change %}disabled{% endif %} rows="2"
                        >{{ form.description.value|default_if_none:"" }}</textarea>
                    </div>
                </div>
                <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_email }}" />
                {% if form.sql.errors %}
                    {% for error in form.sql.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}
                {% endif %}
                <div class="panel panel-default sql-panel">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="panel-title">SQL</span>
                            </div>
                            <div class="col-md-6 text-right">
                                {% if query %}
                                    <small>
                                        <a href="#" title="Open in playground" id="playground_button">
                                            <i class="glyphicon glyphicon-new-window"></i>
                                        </a>
                                    </small>
                                    <small>
                                        <i id="sql_toggle" class="glyphicon glyphicon-resize-full"></i>
                                    </small>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="panel-content">
                        <textarea
                            class="form-control" {% if not can_change %} disabled {% endif %} cols="40" id="id_sql"
                            name="sql" rows="20">{{ form.sql.value|default_if_none:"" }}</textarea>
                    </div>
                    {% if params %}
                        {% include 'explorer/params.html' %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="text-center">
                        {% if can_change %}
                            <div class="btn-group">
                                <input type="submit" value="{% trans 'Save & Run' %}" class="btn btn-primary" id="save_button" />
                                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                                </button>
                                <ul class="dropdown-menu">
                                    {% export_buttons query %}
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <input type="submit" value="{% trans 'Save Only' %}" class="btn btn-link" id="save_only"/>
                                    </li>
                                </ul>
                            </div>
                            <button type="button" class="btn btn-default" id="format_button">
                                {% trans "Format" %}
                            </button>
                            <button type="button" class="btn btn-default" id="show_schema_button">
                                {% trans "Show Schema" %}
                            </button>
                            <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">
                                {% trans "Hide Schema" %}
                            </button>
                        {% else %}
                            <input id="refresh_button" type="submit" value="{% trans 'Refresh' %}" class="btn btn-default" />
                            <div class="btn-group">
                                <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {% trans "Download" %}
                                </label>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                                </button>
                                <ul class="dropdown-menu">
                                    {% export_buttons query %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="" height="828px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>

{% include 'explorer/preview_pane.html' %}

<div class="row">
    <div class="col-md-6">
        {% if query and can_change and tasks_enabled %}
            {{ form.snapshot }} {% blocktrans %}Snapshot{% endblocktrans %}
        {% endif %}
    </div>
    <div class="col-md-6 text-right">
        <small>
            {% if query.avg_duration %}
                {% blocktrans trimmed with avg_duration=query.avg_duration user_email=form.created_by_user_email created=form.created_at_time %}
                    Avg. execution: {{ avg_duration|floatformat:2 }}ms. Query created by {{ user_email }} on {{ created }}.
                {% endblocktrans %}
            {% endif %}
        </small>
    </div>
</div>
{% endblock %}

{% block sql_explorer_scripts %}
    {{ block.super }}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId);

            $('#sql_toggle').on('click', function () {
                $('.panel-content').slideToggle('slow');

                if ($(this).hasClass('glyphicon-resize-full')) {
                    $(this).addClass('glyphicon-resize-small').removeClass('glyphicon-resize-full');
                } else {
                    $(this).addClass('glyphicon-resize-full').removeClass('glyphicon-resize-small');
                }

            })
            {% if query %}
                $('.panel-content').hide();
            {% endif %}
        });
    </script>
{% endblock %}